spring.application.name=fareupdater
server.address=0.0.0.0
server.port=8443
server.ssl.key-store=classpath:Yeti_Private_Key_2026.pfx
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=Goldbed@2020
server.ssl.key-alias=te-5a3794ed-fa62-4155-ae60-32bfcdcbad16


spring.datasource.url=jdbc:sqlserver://SVR2K19_DB\\AVANTIK_DB2017:1433;databaseName=FareUpdate;encrypt=false;trustServerCertificate=true
spring.datasource.username=Reader
spring.datasource.password=Reader@!@#
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.properties.hibernate.use_sql_comments=true
