spring.application.name=fareupdater
server.address=0.0.0.0
server.port=8443
server.ssl.key-store={KEYSTORE}
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password={PASSWORD}
server.ssl.key-alias={ALIAS}


spring.datasource.url={URL}
spring.datasource.username={USERNAME}
spring.datasource.password={PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.properties.hibernate.use_sql_comments=true
